# Generated by Django 2.0.5 on 2018-05-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('telegram', models.CharField(max_length=50)),
                ('eth', models.CharField(max_length=500)),
                ('ethJson', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AirDrop',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('airdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AirDrop')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='airdrop',
            unique_together={('name', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('mobile', 'email', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('account', 'airdrop')},
        ),
    ]
