# Generated by Django 2.0.5 on 2018-05-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180520_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.CharField(default='+86', max_length=10),
        ),
    ]
