# Generated by Django 2.0.5 on 2018-05-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='remark',
            field=models.CharField(default='', max_length=255, verbose_name='备注'),
        ),
    ]
