# Generated by Django 2.0.5 on 2018-05-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180526_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airdrop',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
