# Generated by Django 2.0.5 on 2018-05-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180526_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
