# Generated by Django 2.0.5 on 2018-05-30 08:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='twitter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
