# Generated by Django 2.0.5 on 2018-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_apis_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='链接')),
                ('verified', models.BooleanField(verbose_name='是否被点击过')),
            ],
        ),
    ]
