# Generated by Django 2.0.5 on 2018-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='是否被点击过'),
        ),
    ]
