# Generated by Django 2.0.5 on 2018-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180530_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facebook',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
