# Generated by Django 2.0.5 on 2018-06-01 15:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180601_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='telegram',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='apis',
            name='twitter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
